### ISSUE TITLE
Alphabets are not available on v3.0.0

### ISSUE THREAD

**Issue by quinterojose** [codeyu/nanoid-net#17]
Alphabets are listed in the readme as a feature, but they are not available in the current version. Not a big deal but it's a little confusing to see a feature listed and not be able to use it since it's part of a future release.

**Comment by Petteroe** [comment]
@codeyu I am also looking for a shorter, safe ID and would like the alphabets as documented. But even though the implementation has been in the code for months, it has been almost a year since the last Nuget build. Can you please publish the latest to Nuget?

**Comment by Petteroe** [comment]
One thing; it would be nice to fix this bug before shipping a fresh Nuget:

                public const string NoLookAlikeSafeLetters = NoLookAlikeLettersUppercase + NoLookAlikeLettersLowercase;
                
I have a small PR for this here: https://github.com/codeyu/nanoid-net/pull/19

**Comment by codeyu** [comment]
thank you @Petteroe . v3.1.0 released.
