### ISSUE TITLE
Add table giving a quick reference of collision probabilities?

### ISSUE THREAD

**Issue by pha3z** [codeyu/nanoid-net#5]
I noticed the official ai nanoid also lacks this feature.  Maybe it belongs there, but I'm a .NET guy and I had found this package first. :)

I see there's an option to generate shorter nanoids (and increase collision probability).

I think it would be super handy if there was a table in the read me that showed two columns:  nanoid length and collision probability. Then a person could quickly glance at the table to judge how short of nanoids they could feasibly use for their use case.

The phrasing example in the ai nanoid doc is really nice:
"For there to be a one in a billion chance of duplication, 103 trillion version 4 IDs must be generated."
That's great if I expected to generate 103 trillion IDs.  But I only expect to generate a few billion in my lifetime, so I'd like shorter IDs.

**Comment by viniciuschiele** [comment]
This tool gives the probability based on the length: https://zelark.github.io/nano-id-cc/

**Comment by SasLuca** [comment]
Fixed in #14

**Comment by codeyu** [comment]
thank you. v3.1.0 released.
