### ISSUE TITLE
`using Nanoid;` won't work

### ISSUE THREAD

**Issue by aradalvand** [codeyu/nanoid-net#8]
Hi there. First off, thank you for this package.

It seems like it's not possible to do a `using Nanoid;` at the top of a `.cs` file and then reference the `Nanoid` class in the code. Later `Nanoid` references point to the namespace and not the class:

```csharp
using Nanoid;

string id = Nanoid.Generate(); // ERROR: "The type or namespace name 'GenerateAsync' does not exist in the namespace 'Nanoid'"
```
![image](https://user-images.githubusercontent.com/26527405/235367129-01c1caf8-2c95-44d1-81f0-4ccc287a3f69.png)

Minimal repro: https://github.com/aradalvand/nanoid-namespace-test

Having a type with the same name as its containing namespace is [officially considered bad practice](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces#:~:text=DO%20NOT%20use%20the%20same%20name%20for%20a%20namespace%20and%20a%20type%20in%20that%20namespace.). More importantly in this case, it's basically unusable. You always have to use a fully-qualified name, which is ugly (e.g. `Nanoid.Nanoid.Generate()`)

Please consider changing the name of the namespace to something else, for example, `NanoidNs`, `NanoidGenerator` or anything that would make it different from the class name.

**Comment by codeyu** [comment]
Please use version 3.0.0, thank you.

**Comment by aradalvand** [comment]
Thanks, but I think it would've made more sense to keep tbe namespace as `Nanoid` (to match the NuGet package name) and instead change the class name to something like `NanoidGenerator`.
