### ISSUE TITLE
Each new instance of CryptoRandom replaces the static generator.

### ISSUE THREAD

**Issue by sloncho** [codeyu/nanoid-net#9]
https://github.com/codeyu/nanoid-net/blob/445f4d363e0079e151ea414dab1a9f9961679e7e/src/Nanoid/CryptoRandom.cs#L19

Not sure if this is a problem or not, but looks like it can have negative consequences. The CryptoRandom is used as singleton in NanoId static class, but as CryptoRandom is public, the consumer can create new instances, which in term will replace the static `_r` member, this changing the behavior of the instance used in Nanoid static methods.

Suggestion: make `_r` instance, and not static field. Or use static initializer on L19 instead of constructor initializer.

**Comment by codeyu** [comment]
thank you. v3.1.0 released.
